config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users do
    resources :exercises
  end

  root 'dashboard#index'

  resource :dashboard, only: [:index] do
    collection do
      get :search, to: 'dashboard#search'
    end
  end

  resources :friendships, only: [:show, :create, :destroy]

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @members = User.paginate(page: params[:page])
  end

  def search
    @members = User.search_by_name(params[:search_name]).paginate(page: params[:page])
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="jumbotron">
  <h1>Workout Lounge!</h1>
  <p>Share your workouts with your friends and family</p>
</div>

<div class="row">
  <div class="col-md-10">
    <h2>List of Members</h2>
    <%= will_paginate @members, renderer: BootstrapPagination::Rails, class: 'pull-left paginate' %>
  </div>
</div>

<div class="container">
  <div class="row">
    <% if @members.present? %>
      <% @members.each do |member| %>
        <div class="col-md-10 well member">
          <%= member.full_name %>
          <% if current_user %>
            <%= link_to "Follow", friendships_path(friend_id: member.id), method: :post,
                          class: "btn btn-primary pull-right" unless current_user.follows_or_same?(member) %>
          <% end %>
        </div>
      <% end %>
    <% else %>
      There's no members
    <% end %>
  </div>
</div>

app/views/dashboard/search.html.erb
<div class="row">
  <div class="col-md-10">
    <h2>Result for searching Members</h2>
  </div>
</div>

<div class="row">
  <% if @members.present? %>
    <% @members.each do |member| %>
      <div class="col-md-10 well member">
        <%= member.full_name %>
        <% if current_user %>
          <%= link_to "Follow", friendships_path(friend_id: member.id), method: :post,
                        class: "btn btn-primary pull-right" unless current_user.follows_or_same?(member) %>
        <% end %>
      </div>
    <% end %>
  <%= will_paginate @members, renderer: BootstrapPagination::Rails, class: 'pull-left paginate' %>
  <% else %>
    There's no results
  <% end %>
</div>