config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users do
    resources :exercises
  end

  root 'dashboard#index'

  resource :dashboard, only: [:index] do
    collection do
      get :search, to: 'dashboard#search'
    end
  end

  resources :friendships, only: [:show, :create, :destroy]

end

app/views/shared/_header.html.erb
<header role="banner">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Athletes Den", root_path, class: "navbar-brand" %>
      </div>
      <div id="#bs-example-navbar-collapse-1" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_path, class: "navbar-brand" %>
            <span class="sr-only">(current)</span>
          </li>
        </ul>
        <%= form_tag(search_dashboard_path, method: 'get', class: 'navbar-form navbar-left', role: 'search') do %>
          <div class="form-group">
            <%= text_field_tag :search_name, nil, placeholder: "Search for friends", class: "form-control" %>
          </div>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "My Lounge", user_exercises_path(current_user), class: "navbar-brand" %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navbar-brand" %></li>
            <div class="navbar-right">
              <p class="navbar-text">
                Signed in as <%= current_user.email %>
              </p>
            </div>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path, class: "navbar-brand" %></li>
            <li><%= link_to "Log in", new_user_session_path, class: "navbar-brand" %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>
</header>

app/views/shared/_main.html.erb
<div class="container">
  <div class="col-md-offset-1 col-md-10">
    <%= flash_messages %>
    <%= yield %>
  </div>
</div>