config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users do
    resources :exercises
  end

  root 'dashboard#index'

  resource :dashboard, only: [:index] do
    collection do
      get :search, to: 'dashboard#search'
    end
  end

  resources :friendships, only: [:show, :create, :destroy]

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  def index
    @exercises = current_user.exercises.all
    @friends   = current_user.friends
  end

  def show
  end

  def new
    @exercise = current_user.exercises.build
  end

  def create
    @exercise = current_user.exercises.build(exercise_params)

    if @exercise.save
      flash[:success] = "Exercise has been created"
      redirect_to [current_user, @exercise]
    else
      flash[:alert] = "Exercise has not been created"
      render :new
    end
  end

  def edit
  end

  def update
    if @exercise.update(exercise_params)
      flash[:success] = "Exercise has been updated"
      redirect_to [current_user, @exercise]
    else
      flash[:alert] = "Exercise has not been updated"
      render :edit
    end
  end

  def destroy
    @exercise.destroy
    flash[:success] = "Exercise has been deleted"
    redirect_to user_exercises_path(current_user)
  end

  private

    def exercise_params
      params.require(:exercise).permit(:duration_in_min, :workout, :workout_date, :user)
    end

    def set_exercise
      @exercise = current_user.exercises.unscoped.find(params[:id])
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<div class='row'>
  <div class='col-md-12'>
    <%= form_for([current_user, @exercise], :html=> {class: "form-horizontal", role: "form"}) do |f| %>
      <% if @exercise.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@exercise.errors.count, "error") %>
      prohibited this exercise from being saved: </h2>
          <ul>
            <% @exercise.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :duration_in_min, "Duration (min)" %>
        </div>
        <div class="col-md-10">
          <%= f.number_field :duration_in_min, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :workout, "Workout Details" %>
            <br>
        </div>
        <div class="col-md-10">
          <%= f.text_area :workout, class: "form-control", rows: "10" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :workout_date, "Activity date" %>
        </div>
        <div class="col-md-10">
          <%= f.text_field :workout_date, class: "form-control", id: "workout-date" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/exercises/edit.html.erb
<h1 class="text-center">Edit Exercise for <%= current_user.full_name %></h1>

<%= render 'form' %>

<%= link_to "Show", [current_user, @exercise] %>
<%= link_to "Back", user_exercises_path(current_user) %>

app/views/exercises/index.html.erb
<div class="col-md-8 col-xs-12">
  <% if @exercises.present? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Duration (min)</th>
          <th>Workout details</th>
          <th>Activity date</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @exercises.each do |exercise| %>
          <tr>
            <td><%= exercise.duration_in_min %></td>
            <td><%= truncate(exercise.workout, lengtd: 100) %></td>
            <td><%= exercise.workout_date %></td>
            <td><%= link_to "Show", [current_user, exercise] %></td>
            <td><%= link_to "Edit", [:edit, current_user, exercise] %></td>
            <td><%= link_to "Destroy", [current_user, exercise], method: :delete,
                                      data: {confirm: "Are you sure?"}  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="alert alert-danger message-font text-center" role="alert">
      No workouts yet
    </div>
  <% end %>
  <%= link_to "New Workout", new_user_exercise_path(current_user), class: "btn btn-primary link" %>
  <%= content_tag :div, "", id: "chart", data: { workouts: @exercises } %>
</div>

<div class="col-md-4 col-xs-12 row">
  <h1 class="text-center">My Friends</h1>
  <% @friends.each do |friend| %>
      <div class="row">
        <div class="col-md-offset-1 col-md-6 friend_name text-center">
          <%= link_to friend.full_name, friendship_path(current_user.current_friendship(friend)) %>
        </div>
        <div class="col-md-5">
          <div class="btn-unfollow">
            <%= link_to "Unfollow", friendship_path(current_user.current_friendship(friend)),
                          method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary link" %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/exercises/new.html.erb
<h1 class="text-center">New Exercise for <%= current_user.full_name %></h1>

<%= render 'form' %>

<div class="row">
  <div class="col-md-12">
    <div class="col-md-10 col-md-offset-2">
      <%= link_to "Back", user_exercises_path(current_user), class: "btn btn-primary link", id: "new-exr-btn" %>
    </div>
  </div>
</div>

app/views/exercises/show.html.erb
<div class="col-xs-12 col-md-10 col-md-offset-1">
  <div>
    <h2 class="show-header">Showing <%= "#{@exercise.user.full_name}'s Workout Details" %></h2>
  </div>

  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Duration (min):</strong>
    </div>
    <div class="col-xs-8 text-right" id="duration_in_min">
      <%= @exercise.duration_in_min %>
    </div>
  </div>

  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Workout details:</strong>
    </div>
    <div class="col-xs-8 text-right">
    <%= truncate(@exercise.workout, length: 50) %>
    </div>
  </div>

  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Activity date:</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @exercise.workout_date %>
    </div>
  </div>

  <div class="col-xs-12 col-md-10 member">
  <%= link_to "Back", user_exercises_path(current_user) %>
  </div>
</div>